/* code generated by tsc, og file in the same dir: fill.ts */
var recent: number = 0;
var future: number = 0;
var correct: number = 0;
var wrong: number = 0;

var bar: HTMLInputElement = document.getElementById("bar") as HTMLInputElement;
var count: HTMLElement = document.getElementById("count") as HTMLElement;

var values: number[] = new Array<number>(16);

function pressed(what: number) : void {
	recent <<= 1;
	recent += what;
	recent %= 16;
	values[recent]++;
	if (recent == future) correct++;
	else wrong++;
	future = recent << 1;
	future %= 16;
	let howManyZero: number = values[future];
	let howManyOne: number = values[future + 1];
	if (howManyZero < howManyOne) future++;
	else future += Math.round(Math.random());
	bar.value = (wrong / (correct + wrong)).toString();
	count.innerHTML = (correct + wrong).toString();
}