/* code generated by tsc, og file in the same dir: fill.ts */
var recent = 0;
var future = 0;
var correct = 0;
var wrong = 0;
var bar = document.getElementById("bar");
var count = document.getElementById("count");
var values = new Array(16);
function pressed(what) {
    recent <<= 1;
    recent += what;
    recent %= 16;
    values[recent]++;
    if (recent == future)
        correct++;
    else
        wrong++;
    future = recent << 1;
    future %= 16;
    var howManyZero = values[future];
    var howManyOne = values[future + 1];
    if (howManyZero < howManyOne)
        future++;
    else
        future += Math.round(Math.random());
    bar.value = (wrong / (correct + wrong)).toString();
    count.innerHTML = (correct + wrong).toString();
}
function what() {
    return (future & 1) != 0;
}
console.log("Hello! Type what() to know what button the script thinks you are going to push next.\nCheck out more of my stuff at https://catonif.github.io");
